### ISSUE TITLE
Everything is too small

### ISSUE THREAD

**Issue by HippoDan** [Ghostkeeper/SVGToolpathReader#12]
The imported SVG is not coming out to scale.  My 180mm Square is loading in as 135mm.  I made my SVG in Illustrator drawn in mm.

**Comment by Ghostkeeper** [comment]
Could you share an SVG file that reproduces the problem? I don't have Illustrator available to me so I don't know how Illustrator exactly saves this SVG file.

**Comment by HippoDan** [comment]
Here is the one that was giving me problems.  It's 180mm centered on a 220mm area.  Come in about 80% of the size it should be.

[Square Spiral Bed Test 180mm.svg.zip](https://github.com/Ghostkeeper/SVGToolpathReader/files/5467113/Square.Spiral.Bed.Test.180mm.svg.zip)

**Comment by Ghostkeeper** [comment]
Thanks! I think I can take a look next weekend.

This plug-in takes the build volume as the viewport for the file. This results in a few strange things, like scaling the canvas so that the viewport is correct, so maybe that is the issue that you're running into here. Needs to be refined a bit.

**Comment by Ghostkeeper** [comment]
So this document saves its units in pixels. The document specifies a size of `651.98651px`. SVGToolpathReader assumes a display resolution of 96PPI (as per the [CSS standard](https://www.w3.org/TR/CSS21/syndata.html#length-units) which specifies that a reference pixel is 0.75pt and a pt is 1/72 inch). This would result in a canvas size of [172.5mm](https://www.wolframalpha.com/input/?i=651.96851+pixels+%2F+96pixels%2Finch). Since the viewbox is the same as the document width, the default units of the document are the same as the pixel size.

The spiral in the image is a polyline that ranges from X coordinate `70.5204` to `580.7561` (and very similar Y coordinates). That's a width of `510.2357` units. So that should indeed have a width of [135mm](https://www.wolframalpha.com/input/?i=%28580.7561-70.5204%29pixels%2F96ppi).

I think that Illustrator may be using a pixel density of 72ppi. This is an ancient standard set by Apple in the 1980s. If so, it's not saving it to the document since the SVG source code doesn't contain the PPI anywhere:

```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 23.0.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.0" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="651.96851px" height="651.96851px" viewBox="0 0 651.96851 651.96851"
	 style="enable-background:new 0 0 651.96851 651.96851;" xml:space="preserve">
<style type="text/css">
	.st0{fill:none;stroke:#000000;stroke-width:1.41732;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;}
</style>
<polyline class="st0" points="70.5204,552.1015 553.75592,552.1015 553.75592,97.86616 99.5206,97.86616 99.52011,501.40829 
	497.06274,501.40833 497.06274,154.55898 157.21342,154.55898 157.21294,444.71509 440.36945,444.71503 440.36945,211.25179 
	213.90623,211.25179 213.90575,388.02179 383.67612,388.02173 383.67612,267.9451 270.59955,267.9451 270.59906,331.32849 
	315.98276,331.32843 315.98276,297.63803 353.983,297.63803 353.983,354.3284 240.59885,354.32846 240.59933,240.94472 
	410.67633,240.94472 410.67633,411.0217 183.90555,411.02176 183.90604,184.25142 468.36963,184.25142 468.36963,469.71503 
	128.21274,467.71506 128.21323,127.5586 524.06293,127.5586 524.06293,524.40833 70.51991,524.40826 70.5204,70.86578 
	580.7561,70.86578 580.7561,581.1015 70.5204,581.1015 "/>
</svg>
```

So I think there is nothing that the SVGToolpathReader is doing wrong here. The size of the square in the document is indeed 135mm. Illustrator may have been using a different DPI than the W3C standard, but this is not apparent from the SVG document. Sorry!
Indeed, when printing this on my 2D printer through Inkscape I end up with a width of about 134.5mm. My 2D printer is probably slightly off, but it's close enough to what's in the document.

I've rescaled your document to correctly use 96ppi (so 133.3333% scale): [Square Spiral Bed Test 180mm 96ppi.zip](https://github.com/Ghostkeeper/SVGToolpathReader/files/5506351/Square.Spiral.Bed.Test.180mm.96ppi.zip)

**Comment by Ghostkeeper** [comment]
Note that the document also specifies a line width of 1.8mm. This is probably too wide for your nozzle to handle so I don't expect that printing it this way would end up well.
