### ISSUE TITLE
Doesn't include some curves

### ISSUE THREAD

**Issue by BagelOrb** [Ghostkeeper/SVGToolpathReader#14]
Some curves are missing sometimes.

Input:
![image](https://user-images.githubusercontent.com/8895761/136379521-825b7689-3912-4667-9cd5-3303ceb92701.png)
[hello.zip](https://github.com/Ghostkeeper/SVGToolpathReader/files/7302993/hello.zip)

Output:
![image](https://user-images.githubusercontent.com/8895761/136379568-eef5850f-df8f-4d11-bda0-0ec202bf45e1.png)

Cura 4.11

**Comment by BagelOrb** [comment]
Idk "hell" might be a bit of an overreaction to a minor bug like this 😉

**Comment by Ghostkeeper** [comment]
Definitely looks like a bug to me, indeed! I wonder what's different about those curves that they aren't included.

I'm not doing a whole lot of maintenance on this plug-in any more (partially because it ended up exploding in complexity way beyond what its architecture was meant to take on) but I'll see what I can do to fix this. I don't expect it'll be too difficult to fix.

**Comment by Ghostkeeper** [comment]
Inside the file it's a cubic curve with more than the minimum number of handles.

    c 2.338008,0 4.233337,-1.89533 4.233333,-4.23334 -2e-6,-2.338 -1.895329,-4.23333 -4.233333,-4.23333 -2.338004,0 -4.233329,1.89533 -4.233333,4.23333 -2e-6,1.35094 0.632798,2.55409 1.618157,3.32919

Looks like it's only doing the first part of the cubic curve. It should re-use the previous handles to continue the curve with the new, extra handles for the next bit. That's definitely a bug.

**Comment by Ghostkeeper** [comment]
Turns out the problem was with scientific notation.

It was properly parsing the scientific notation as a number. It was also properly handling cubic curves with more than 6 parameters as it should. However it was recognising the `e` in `-2e-6` as a new command. So rather than processing those parameters as part of the last `c` command (to denote a relative cubic curve), it processed them as being part of an `e` command. It then discarded them as an unknown command.

Fixed this up for the next version. Works now!
![image](https://user-images.githubusercontent.com/2448634/136656905-05be2515-89cd-4732-aa95-c6200fd8f2c0.png)

**Comment by BagelOrb** [comment]
Awesome! Good busy!

**Comment by Ghostkeeper** [comment]
The current master branch has 3 bug fixes over the latest version on the Marketplace. I might release a bugfix version with those 3 fixes in soonish.
